### PR TITLE
initial revision

### PR DESCRIPTION
**Pull request by sabernar**
General Xcode project structure with some added libraries (AFNetworking, etc.).  I set it up as an Objective-C project, but can switch it to Swift if that is preferred.

### CODE REVIEW

**Comment by jherskowitz** [comment]
Thanks!

**Comment by jherskowitz** [comment]
Thanks

**Comment by muesli** [comment]
Saw UIImage, SDImageCache and a few others referencing LICENSE files, which are missing. Just wondering which license they're released under.

Also, do we actually wanna import third-party libs here instead of letting the build system find them? Maybe a git submodule at least?

**Comment by jherskowitz** [comment]
@sabernar?

**Pull request merged**
